# ---------------------------------------------------------------
# HPC Carpentries in the Cloud: Slurm + Software Stack from EESSI
# ---------------------------------------------------------------
#
# The HPC Carpentry Cluster in the Cloud is provided as a public
# service by volunteers. It is provisioned with Magic Castle
# <https://github.com/ComputeCanada/magic_castle> using the EESSI
# <https://eessi.github.io/docs/> software stack. If you need an
# account, please visit <cluster.hpc-carpentry.org>.
#
# Compute responsibly.
---

snippets: "/snippets_library/SRC_Sherlock_slurm"

local:
  prompt: "[you@laptop:~]$"
  bash_shebang: "#!/usr/bin/env bash"

remote:
  name: "Sherlock"
  login: "login.sherlock.stanford.edu"
  portal: "https://ondemand.sherlock.stanford.edu"
  host: "sh03-ln01"
  node: "smnode1"
  location: "cluster.hpc-carpentry.org"
  homedir: "/home/users"
  user: "SUNetID"
  module_python3: "Python"
  prompt: "[SUNetID@sh03-ln01 login ~]$"
  bash_shebang: "#!/bin/bash"

sched:
  name: "Slurm"
  submit:
    name: "sbatch"
    options: ""
  queue:
    debug: "smnode"
    testing: "cpubase_bycore_b1"
  status: "squeue"
  flag:
    user: "-u yourUsername"
    interactive: ""
    histdetail: "-l -j"
    name: "-J"
    time: "-t"
    queue: "-p"
  del: "scancel"
  interactive: "srun"
  info: "sinfo"
  comment: "#SBATCH"
  hist: "sacct -u yourUsername"
  hist_filter: ""

episode_order:
  - 10-hpc-intro
  - 11-connecting
  - 12-cluster
  - 13-scheduler
  - 14-environment-variables
  - 15-modules
  - 16-transferring-files
  - 17-parallel
  - 18-resources
  - 19-responsibility
